sourceDir     = "source"
destDir       = "public"
postsDir      = "source/_posts"
layoutsDir    = "source/_layouts"
postLayoutsDir = "source/_post_layouts"
includesDir = "source/_includes"

[Site]
Title = "Your Blog Title"
Author = "Your Name"
Description = "A description of your blog"
