sourceDir     = "source"
destDir       = "public"
postsDir      = "_posts"
layoutsDir    = "_layouts"
viewsDir      = "_views"

[Site]
Title = "Alex Browne's Blog"
Author = "Alex Browne"
Description = "A blog written by Alex Browne about coding and shit."
