sourceDir     = "source"
destDir       = "public"
postsDir      = "source/_posts"
layoutsDir    = "source/_layouts"
postLayoutsDir = "source/_post_layouts"
includesDir = "source/_includes"

[Site]
Title = "Alex Browne's Blog"
Author = "Alex Browne"
Description = "A blog written by Alex Browne about coding and shit."
